kevin_platform:
    resource: "@KevinPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
    path: /login
    defaults:
        _controller: KevinUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout